import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/common/Background";
import Inicio from "@/components/home/Inicio";
import Footer from "@/components/home/footer";
import Header from "@/components/app/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-full font-serif overflow-x-hidden overflow-y-auto flex flex-col items-center">
        <Header/>
        <Inicio/>
        <Footer/>
      </body>
    </html>
  );
}
